name: Build & Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install build
      - run: python -m build
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
